Style/Documentation:
  Enabled: false

Style/NonNilCheck:
  IncludeSemanticChanges: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'lib/cancan/matchers.rb'
    - '**/*_spec.rb'

# TODO
# Offense count: 2
# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist.
# NamePrefix: is_, has_, have_
# NamePrefixBlacklist: is_, has_, have_
# NameWhitelist: is_a?
Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'lib/cancan/ability.rb'

# TODO
Lint/AmbiguousBlockAssociation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.2.0
  Exclude:
    - 'gemfiles/vendor/bundle/**/*'
    - 'Appraisals'

inherit_from: .rubocop_todo.yml
